;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	keyboard-escape-quit
	mouse-drag-tab-line
	))

(setq mc/cmds-to-run-once
      '(
	suspend-frame
	xref-go-forward
	yaml-electric-backspace
	))
