;;; mood-one-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from mood-one-theme.el

(autoload 'mood-one-theme-neotree-configuration-enable "mood-one-theme" "\
Enable custom mood-one configuration for use with neotree.")
(autoload 'mood-one-theme-arrow-fringe-bmp-enable "mood-one-theme" "\
Enable custom mood-one fringe bitmaps to replace the default line continuation and line wrap arrows.")
(autoload 'mood-one-theme-diff-hl-fringe-bmp-function "mood-one-theme" "\
Fringe bitmap function for use as `diff-hl-fringe-bmp-function'.

(fn TYPE POS)")
(autoload 'mood-one-theme-flycheck-fringe-bmp-enable "mood-one-theme" "\
Enable custom mood-one fringe bitmaps for use with flycheck.")
(autoload 'mood-one-theme-flymake-fringe-bmp-enable "mood-one-theme" "\
Enable custom mood-one fringe bitmaps for use with flymake.")
(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "mood-one-theme" '("mood-one"))

;;; End of scraped data

(provide 'mood-one-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mood-one-theme-autoloads.el ends here
